### PR TITLE
Throw exception on uninitialized non-nullable property.

### LINKED ISSUE #8: Uninitialized support
Uninitialized values are now set to `null`: https://github.com/spatie/value-object/blob/master/src/ValueObject.php#L23

To be more in line with the type system that PHP 7.4 brings, we should add another state to the property, so that there's a difference between `null` and `uninitialized`.

It should be something like this:

```php
foreach ($properties as $property) {
    if (
        ! isset($parameters[$property->getName()]) 
        && ! $property->isNullable
    ) {
        throw ValueObjectException::uninitialized($property);
    }

    $value = $parameters[$property->getName()] ?? null;
    
    $property->set($value);
}
```

Small remark: `ValueObjectException::uninitialisedProperty` may be renamed to `ValueObjectException::uninitialized`.

### PR DESCRIPTION
**Pull request by hulkur**
Resolves #8.

Changed default value for `Property::$isNullable` to `true` to be consistent with test `empty_type_declaration_allows_everything`.

Added test to allow only explicitly specified nullable property.

### CODE REVIEW

File: src/Property.php [hunk 1]
```diff
@@ -19,7 +19,7 @@ class Property extends ReflectionProperty
     protected $hasTypeDeclaration = false;
 
     /** @var bool */
-    protected $isNullable = false;
+    protected $isNullable = true;
```
Comment (brendt) [inline src/Property.php]: Why did you change the default value to `true`? I prefer this package to be non-nullable by default, als it prevents lots of bugs.

Comment (hulkur) [reply src/Property.php]: As explained in PR: to be consistent with test `empty_type_declaration_allows_everything`.
If it is left `false`, then this test breaks.

Comment (hulkur) [reply src/Property.php]: Ok, will take a look

**Comment by brendt** [comment]
Looks good! I'll merge this later today or tomorrow.

**Comment by brendt** [comment]
Thanks again!
